@startuml

start
if(是否有el属性) then(true)
else
    if(是否调用$mount函数挂载节点) then(true)
    else 
        stop
    endif    
endif

if(是否有template属性) then(true)
    :解析template中的字符串，生成抽象语法书(AST);
else 
    :根据挂载的元素找到其outerHTML;
    :解析outerHTML获取的字符串，生成抽象语法书(AST);
endif   

:利用render函数，生成虚拟dom;
:将虚拟DOM，生成真实的DOM;
:用生成的真实DOM，替换挂载的DOM元素;
stop

@enduml
