@startuml

start
note right
在**React节点**中持有对函数组件的引用以及状态数组的引用，
因此，每次重新调用函数组件时，能正确的找到该函数的状态数组
end note

:第N次调用useState;
if(检查该节点的状态数组是否存在下标N) then(不存在)
    :使用默认值创建一个状态;
    :将该状态加入到状态数组中，下标为N;
else(不存在)
    :忽略掉默认值;
    :直接得到状态值;
endif


stop



@enduml